version: "3.8"

services:
  binotify-soap:
    container_name: binotify-soap
    image: binotify-soap:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REST_API_KEY=123456789
      - APP_API_KEY=987654321
