version: "3.8"

services:
  sabun:
    container_name: sabun
    image: binotify-soap:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
